{
//=========Macro generated from canvas: c01/
//=========  (Sun Sep 16 08:04:20 2018) by ROOT version5.34/18
   TCanvas *c01 = new TCanvas("c01", "",0,0,700,500);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c01->Range(-45.18072,-2.02393,1581.325,2.655992);
   c01->SetFillColor(0);
   c01->SetBorderMode(0);
   c01->SetBorderSize(2);
   c01->SetLogy();
   c01->SetTickx(1);
   c01->SetTicky(1);
   c01->SetLeftMargin(0.12);
   c01->SetRightMargin(0.05);
   c01->SetTopMargin(0.05);
   c01->SetBottomMargin(0.13);
   c01->SetFrameFillStyle(0);
   c01->SetFrameBorderMode(0);
   c01->SetFrameFillStyle(0);
   c01->SetFrameBorderMode(0);
   
   THStack *Mstack = new THStack();
   Mstack->SetName("Mstack");
   Mstack->SetTitle("");
   Mstack->SetMinimum(0.1);
   Mstack->SetMaximum(160.9878);
   Double_t xAxis61[6] = {150, 400, 600, 800, 1000, 1500}; 
   
   TH1F *Mstack_stack_11 = new TH1F("Mstack_stack_11","",5, xAxis61);
   Mstack_stack_11->SetMinimum(0.03841136);
   Mstack_stack_11->SetMaximum(264.2386);
   Mstack_stack_11->SetDirectory(0);
   Mstack_stack_11->SetStats(0);
   Mstack_stack_11->SetLineStyle(0);
   Mstack_stack_11->SetMarkerStyle(20);
   Mstack_stack_11->GetXaxis()->SetTitle("ZGmass (GeV) ");
   Mstack_stack_11->GetXaxis()->SetLabelFont(42);
   Mstack_stack_11->GetXaxis()->SetLabelOffset(0.007);
   Mstack_stack_11->GetXaxis()->SetLabelSize(0.05);
   Mstack_stack_11->GetXaxis()->SetTitleOffset(1.5);
   Mstack_stack_11->GetXaxis()->SetTitleFont(42);
   Mstack_stack_11->GetYaxis()->SetTitle("Events /bin");
   Mstack_stack_11->GetYaxis()->SetLabelFont(42);
   Mstack_stack_11->GetYaxis()->SetLabelOffset(0.007);
   Mstack_stack_11->GetYaxis()->SetLabelSize(0.05);
   Mstack_stack_11->GetYaxis()->SetTitleOffset(1.25);
   Mstack_stack_11->GetYaxis()->SetTitleFont(42);
   Mstack_stack_11->GetZaxis()->SetLabelFont(42);
   Mstack_stack_11->GetZaxis()->SetLabelOffset(0.007);
   Mstack_stack_11->GetZaxis()->SetLabelSize(0.05);
   Mstack_stack_11->GetZaxis()->SetTitleSize(0.06);
   Mstack_stack_11->GetZaxis()->SetTitleFont(42);
   Mstack->SetHistogram(Mstack_stack_11);
   
   Double_t xAxis62[6] = {150, 400, 600, 800, 1000, 1500}; 
   
   TH1D *ZG_optimal_bkg_nominal = new TH1D("ZG_optimal_bkg_nominal"," ",5, xAxis62);
   ZG_optimal_bkg_nominal->SetBinContent(0,0.02663877);
   ZG_optimal_bkg_nominal->SetBinContent(1,1.078235);
   ZG_optimal_bkg_nominal->SetBinContent(2,0.8740875);
   ZG_optimal_bkg_nominal->SetBinContent(3,0.005950368);
   ZG_optimal_bkg_nominal->SetBinContent(4,-0.03366215);
   ZG_optimal_bkg_nominal->SetBinError(0,0.07505139);
   ZG_optimal_bkg_nominal->SetBinError(1,0.3566535);
   ZG_optimal_bkg_nominal->SetBinError(2,0.4335495);
   ZG_optimal_bkg_nominal->SetBinError(3,0.09091978);
   ZG_optimal_bkg_nominal->SetBinError(4,0.05072643);
   ZG_optimal_bkg_nominal->SetEntries(264);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#00cc00");
   ZG_optimal_bkg_nominal->SetFillColor(ci);

   ci = TColor::GetColor("#00cc00");
   ZG_optimal_bkg_nominal->SetLineColor(ci);

   ci = TColor::GetColor("#00cc00");
   ZG_optimal_bkg_nominal->SetMarkerColor(ci);
   ZG_optimal_bkg_nominal->GetXaxis()->SetLabelFont(42);
   ZG_optimal_bkg_nominal->GetXaxis()->SetLabelSize(0.035);
   ZG_optimal_bkg_nominal->GetXaxis()->SetTitleSize(0.035);
   ZG_optimal_bkg_nominal->GetXaxis()->SetTitleFont(42);
   ZG_optimal_bkg_nominal->GetYaxis()->SetLabelFont(42);
   ZG_optimal_bkg_nominal->GetYaxis()->SetLabelSize(0.035);
   ZG_optimal_bkg_nominal->GetYaxis()->SetTitleSize(0.035);
   ZG_optimal_bkg_nominal->GetYaxis()->SetTitleFont(42);
   ZG_optimal_bkg_nominal->GetZaxis()->SetLabelFont(42);
   ZG_optimal_bkg_nominal->GetZaxis()->SetLabelSize(0.035);
   ZG_optimal_bkg_nominal->GetZaxis()->SetTitleSize(0.035);
   ZG_optimal_bkg_nominal->GetZaxis()->SetTitleFont(42);
   Mstack->Add(ZG_optimal_bkg_nominal,"");
   Double_t xAxis63[6] = {150, 400, 600, 800, 1000, 1500}; 
   
   TH1D *ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal = new TH1D("ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal"," ",5, xAxis63);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetBinContent(1,1.664765);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetBinContent(2,0.45732);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetBinError(1,0.5037067);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetBinError(2,0.3577074);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetEntries(15);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetFillColor(7);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetLineColor(7);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetMarkerColor(7);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetXaxis()->SetLabelFont(42);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetXaxis()->SetLabelSize(0.035);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetXaxis()->SetTitleSize(0.035);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetXaxis()->SetTitleFont(42);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetYaxis()->SetLabelFont(42);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetYaxis()->SetLabelSize(0.035);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetYaxis()->SetTitleSize(0.035);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetYaxis()->SetTitleFont(42);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetZaxis()->SetLabelFont(42);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetZaxis()->SetLabelSize(0.035);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetZaxis()->SetTitleSize(0.035);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetZaxis()->SetTitleFont(42);
   Mstack->Add(ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal,"");
   Double_t xAxis64[6] = {150, 400, 600, 800, 1000, 1500}; 
   
   TH1D *ZG_optimal_ZA_nominal = new TH1D("ZG_optimal_ZA_nominal"," ",5, xAxis64);
   ZG_optimal_ZA_nominal->SetBinContent(0,0.3785068);
   ZG_optimal_ZA_nominal->SetBinContent(1,26.32657);
   ZG_optimal_ZA_nominal->SetBinContent(2,7.094595);
   ZG_optimal_ZA_nominal->SetBinContent(3,1.860419);
   ZG_optimal_ZA_nominal->SetBinContent(4,1.172819);
   ZG_optimal_ZA_nominal->SetBinContent(5,0.4195072);
   ZG_optimal_ZA_nominal->SetBinContent(6,0.1008541);
   ZG_optimal_ZA_nominal->SetBinError(0,0.2288072);
   ZG_optimal_ZA_nominal->SetBinError(1,1.936701);
   ZG_optimal_ZA_nominal->SetBinError(2,1.063575);
   ZG_optimal_ZA_nominal->SetBinError(3,0.5981919);
   ZG_optimal_ZA_nominal->SetBinError(4,0.3836628);
   ZG_optimal_ZA_nominal->SetBinError(5,0.3175832);
   ZG_optimal_ZA_nominal->SetBinError(6,0.1471924);
   ZG_optimal_ZA_nominal->SetEntries(795);
   ZG_optimal_ZA_nominal->SetFillColor(6);
   ZG_optimal_ZA_nominal->SetLineColor(6);
   ZG_optimal_ZA_nominal->SetMarkerColor(6);
   ZG_optimal_ZA_nominal->GetXaxis()->SetLabelFont(42);
   ZG_optimal_ZA_nominal->GetXaxis()->SetLabelSize(0.035);
   ZG_optimal_ZA_nominal->GetXaxis()->SetTitleSize(0.035);
   ZG_optimal_ZA_nominal->GetXaxis()->SetTitleFont(42);
   ZG_optimal_ZA_nominal->GetYaxis()->SetLabelFont(42);
   ZG_optimal_ZA_nominal->GetYaxis()->SetLabelSize(0.035);
   ZG_optimal_ZA_nominal->GetYaxis()->SetTitleSize(0.035);
   ZG_optimal_ZA_nominal->GetYaxis()->SetTitleFont(42);
   ZG_optimal_ZA_nominal->GetZaxis()->SetLabelFont(42);
   ZG_optimal_ZA_nominal->GetZaxis()->SetLabelSize(0.035);
   ZG_optimal_ZA_nominal->GetZaxis()->SetTitleSize(0.035);
   ZG_optimal_ZA_nominal->GetZaxis()->SetTitleFont(42);
   Mstack->Add(ZG_optimal_ZA_nominal,"");
   Double_t xAxis65[6] = {150, 400, 600, 800, 1000, 1500}; 
   
   TH1D *ZG_optimal_outZA_EWK_nominal = new TH1D("ZG_optimal_outZA_EWK_nominal"," ",5, xAxis65);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(0,0.09984028);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(1,11.17737);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(2,3.87781);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(3,1.419295);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(4,0.48221);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(5,0.4134136);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(6,0.06689874);
   ZG_optimal_outZA_EWK_nominal->SetBinError(0,0.03535996);
   ZG_optimal_outZA_EWK_nominal->SetBinError(1,0.3806764);
   ZG_optimal_outZA_EWK_nominal->SetBinError(2,0.2258146);
   ZG_optimal_outZA_EWK_nominal->SetBinError(3,0.1362039);
   ZG_optimal_outZA_EWK_nominal->SetBinError(4,0.08041232);
   ZG_optimal_outZA_EWK_nominal->SetBinError(5,0.07345107);
   ZG_optimal_outZA_EWK_nominal->SetBinError(6,0.02998636);
   ZG_optimal_outZA_EWK_nominal->SetEntries(1449);

   ci = TColor::GetColor("#ffff00");
   ZG_optimal_outZA_EWK_nominal->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   ZG_optimal_outZA_EWK_nominal->SetLineColor(ci);

   ci = TColor::GetColor("#ffff00");
   ZG_optimal_outZA_EWK_nominal->SetMarkerColor(ci);
   ZG_optimal_outZA_EWK_nominal->SetMarkerStyle(21);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetLabelFont(42);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetLabelSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetTitleSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetTitleFont(42);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetLabelFont(42);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetLabelSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetTitleSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetTitleFont(42);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetLabelFont(42);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetLabelSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetTitleSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetTitleFont(42);
   Mstack->Add(ZG_optimal_outZA_EWK_nominal,"");
   Mstack->Draw("bar hist");
   Double_t xAxis66[6] = {150, 400, 600, 800, 1000, 1500}; 
   
   TH1D *ZG_optimal_outZA_EWK_nominal = new TH1D("ZG_optimal_outZA_EWK_nominal"," ",5, xAxis66);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(0,0.5049858);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(1,40.26714);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(2,12.37323);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(3,3.399313);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(4,1.748739);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(5,4.874719);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(6,0.1677528);
   ZG_optimal_outZA_EWK_nominal->SetBinError(0,0.243384);
   ZG_optimal_outZA_EWK_nominal->SetBinError(1,2.068006);
   ZG_optimal_outZA_EWK_nominal->SetBinError(2,1.22397);
   ZG_optimal_outZA_EWK_nominal->SetBinError(3,0.6202028);
   ZG_optimal_outZA_EWK_nominal->SetBinError(4,0.3952676);
   ZG_optimal_outZA_EWK_nominal->SetBinError(5,0.3259665);
   ZG_optimal_outZA_EWK_nominal->SetBinError(6,0.1502158);
   ZG_optimal_outZA_EWK_nominal->SetEntries(2533);

   ci = TColor::GetColor("#ff0000");
   ZG_optimal_outZA_EWK_nominal->SetLineColor(ci);
   ZG_optimal_outZA_EWK_nominal->SetLineWidth(2);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetLabelFont(42);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetLabelSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetTitleSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetTitleFont(42);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetLabelFont(42);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetLabelSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetTitleSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetTitleFont(42);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetLabelFont(42);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetLabelSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetTitleSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetTitleFont(42);
   ZG_optimal_outZA_EWK_nominal->Draw("hist same");
   
   TLegend *leg = new TLegend(0.5,0.78,0.65,0.91,NULL,"brNDC");
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(10);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("ZG_optimal_outZA_EWK_nominal","VBS ZA","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ZG_optimal_ZA_nominal","QCD ZA","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal","non-prompt","f");
   entry->SetFillColor(7);
   entry->SetFillStyle(1001);
   entry->SetLineColor(7);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ZG_optimal_bkg_nominal","Other Bkg","f");

   ci = TColor::GetColor("#00cc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00cc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ZG_optimal_outZA_EWK_nominal","fT2=-1.80e-12","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.21,0.84,"Preliminary");
tex->SetNDC();
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.21,0.88,"CMS");
tex->SetNDC();
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.76,0.96,"35.862 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   c01->Modified();
   c01->cd();
   c01->SetSelected(c01);
}
