#!/bin/bash

crab resubmit -d crab_DE16B-v1
crab resubmit -d crab_DEle16C-v1 
crab resubmit -d crab_DEle16D-v1 
crab resubmit -d crab_DEle16E-v1 
crab resubmit -d crab_DEle16F-v1 
crab resubmit -d crab_DEle16G-v1 
crab resubmit -d crab_DEle16H-v2 
crab resubmit -d crab_DEle16H-v3 

crab resubmit -d crab_DMu16H-v2 
crab resubmit -d crab_DMu16H-v3
crab resubmit -d crab_DMu16G-v1
crab resubmit -d crab_DMu16F-v1
crab resubmit -d crab_DMu16E-v1
crab resubmit -d crab_DMu16D-v1
crab resubmit -d crab_DMu16C-v1
crab resubmit -d crab_DMu16B-v2
crab resubmit -d crab_Z-DY-fxfx
crab resubmit -d crab_STt-1
crab resubmit -d crab_Z-STbart-1
crab resubmit -d crab_Z-STs-1
crab resubmit -d crab_Z-ST-tbarw-1
crab resubmit -d crab_Z-ST-tw-1
crab resubmit -d crab_Z-TTA-1
crab resubmit -d crab_Z-TTA-2
crab resubmit -d crab_Z-TTJets-1
crab resubmit -d crab_Z-WA-1
crab resubmit -d crab_Z-WA-2
crab resubmit -d crab_Z-WJets-2
crab resubmit -d crab_Z-WJets-1
#crab resubmit -d crab_Z-WW-1
#crab resubmit -d crab_Z-WW-2
#crab resubmit -d crab_Z-WZ-1
#crab resubmit -d crab_Z-WZ-2
crab resubmit -d crab_Z-ZA-1
crab resubmit -d crab_Z-ZA-private
#crab resubmit -d crab_Z-ZA-EWK-1
#crab resubmit -d crab_Z-ZZ-1
#crab resubmit -d crab_Z-ZZ-2
