{
//=========Macro generated from canvas: c01/
//=========  (Wed Nov  7 08:59:51 2018) by ROOT version5.34/18
   TCanvas *c01 = new TCanvas("c01", "",0,0,700,500);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c01->Range(-45.18072,-2.040252,1581.325,2.725634);
   c01->SetFillColor(0);
   c01->SetBorderMode(0);
   c01->SetBorderSize(2);
   c01->SetLogy();
   c01->SetTickx(1);
   c01->SetTicky(1);
   c01->SetLeftMargin(0.12);
   c01->SetRightMargin(0.05);
   c01->SetTopMargin(0.05);
   c01->SetBottomMargin(0.13);
   c01->SetFrameFillStyle(0);
   c01->SetFrameBorderMode(0);
   c01->SetFrameFillStyle(0);
   c01->SetFrameBorderMode(0);
   
   THStack *Mstack = new THStack();
   Mstack->SetName("Mstack");
   Mstack->SetTitle("");
   Mstack->SetMinimum(0.1);
   Mstack->SetMaximum(185.7221);
   Double_t xAxis79[6] = {150, 400, 600, 800, 1000, 1500}; 
   
   TH1F *Mstack_stack_14 = new TH1F("Mstack_stack_14","",5, xAxis79);
   Mstack_stack_14->SetMinimum(0.03795885);
   Mstack_stack_14->SetMaximum(307.1422);
   Mstack_stack_14->SetDirectory(0);
   Mstack_stack_14->SetStats(0);
   Mstack_stack_14->SetLineStyle(0);
   Mstack_stack_14->SetMarkerStyle(20);
   Mstack_stack_14->GetXaxis()->SetTitle("ZGmass (GeV) ");
   Mstack_stack_14->GetXaxis()->SetLabelFont(42);
   Mstack_stack_14->GetXaxis()->SetLabelOffset(0.007);
   Mstack_stack_14->GetXaxis()->SetLabelSize(0.05);
   Mstack_stack_14->GetXaxis()->SetTitleOffset(1.5);
   Mstack_stack_14->GetXaxis()->SetTitleFont(42);
   Mstack_stack_14->GetYaxis()->SetTitle("Events /bin");
   Mstack_stack_14->GetYaxis()->SetLabelFont(42);
   Mstack_stack_14->GetYaxis()->SetLabelOffset(0.007);
   Mstack_stack_14->GetYaxis()->SetLabelSize(0.05);
   Mstack_stack_14->GetYaxis()->SetTitleOffset(1.25);
   Mstack_stack_14->GetYaxis()->SetTitleFont(42);
   Mstack_stack_14->GetZaxis()->SetLabelFont(42);
   Mstack_stack_14->GetZaxis()->SetLabelOffset(0.007);
   Mstack_stack_14->GetZaxis()->SetLabelSize(0.05);
   Mstack_stack_14->GetZaxis()->SetTitleSize(0.06);
   Mstack_stack_14->GetZaxis()->SetTitleFont(42);
   Mstack->SetHistogram(Mstack_stack_14);
   
   Double_t xAxis80[6] = {150, 400, 600, 800, 1000, 1500}; 
   
   TH1D *ZG_optimal_bkg_nominal = new TH1D("ZG_optimal_bkg_nominal"," ",5, xAxis80);
   ZG_optimal_bkg_nominal->SetBinContent(0,-0.0001428499);
   ZG_optimal_bkg_nominal->SetBinContent(1,1.077054);
   ZG_optimal_bkg_nominal->SetBinContent(2,0.9015096);
   ZG_optimal_bkg_nominal->SetBinContent(3,0.006491357);
   ZG_optimal_bkg_nominal->SetBinContent(4,-0.03366215);
   ZG_optimal_bkg_nominal->SetBinError(0,0.07011031);
   ZG_optimal_bkg_nominal->SetBinError(1,0.358487);
   ZG_optimal_bkg_nominal->SetBinError(2,0.4310893);
   ZG_optimal_bkg_nominal->SetBinError(3,0.09899319);
   ZG_optimal_bkg_nominal->SetBinError(4,0.05072643);
   ZG_optimal_bkg_nominal->SetEntries(264);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#00cc00");
   ZG_optimal_bkg_nominal->SetFillColor(ci);

   ci = TColor::GetColor("#00cc00");
   ZG_optimal_bkg_nominal->SetLineColor(ci);

   ci = TColor::GetColor("#00cc00");
   ZG_optimal_bkg_nominal->SetMarkerColor(ci);
   ZG_optimal_bkg_nominal->GetXaxis()->SetLabelFont(42);
   ZG_optimal_bkg_nominal->GetXaxis()->SetLabelSize(0.035);
   ZG_optimal_bkg_nominal->GetXaxis()->SetTitleSize(0.035);
   ZG_optimal_bkg_nominal->GetXaxis()->SetTitleFont(42);
   ZG_optimal_bkg_nominal->GetYaxis()->SetLabelFont(42);
   ZG_optimal_bkg_nominal->GetYaxis()->SetLabelSize(0.035);
   ZG_optimal_bkg_nominal->GetYaxis()->SetTitleSize(0.035);
   ZG_optimal_bkg_nominal->GetYaxis()->SetTitleFont(42);
   ZG_optimal_bkg_nominal->GetZaxis()->SetLabelFont(42);
   ZG_optimal_bkg_nominal->GetZaxis()->SetLabelSize(0.035);
   ZG_optimal_bkg_nominal->GetZaxis()->SetTitleSize(0.035);
   ZG_optimal_bkg_nominal->GetZaxis()->SetTitleFont(42);
   Mstack->Add(ZG_optimal_bkg_nominal,"");
   Double_t xAxis81[6] = {150, 400, 600, 800, 1000, 1500}; 
   
   TH1D *ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal = new TH1D("ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal"," ",5, xAxis81);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetBinContent(1,4.012397);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetBinContent(2,0.45732);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetBinContent(3,0.518606);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetBinError(1,1.184978);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetBinError(2,0.3577074);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetBinError(3,0.518606);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetEntries(21);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetFillColor(7);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetLineColor(7);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->SetMarkerColor(7);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetXaxis()->SetLabelFont(42);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetXaxis()->SetLabelSize(0.035);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetXaxis()->SetTitleSize(0.035);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetXaxis()->SetTitleFont(42);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetYaxis()->SetLabelFont(42);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetYaxis()->SetLabelSize(0.035);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetYaxis()->SetTitleSize(0.035);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetYaxis()->SetTitleFont(42);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetZaxis()->SetLabelFont(42);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetZaxis()->SetLabelSize(0.035);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetZaxis()->SetTitleSize(0.035);
   ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal->GetZaxis()->SetTitleFont(42);
   Mstack->Add(ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal,"");
   Double_t xAxis82[6] = {150, 400, 600, 800, 1000, 1500}; 
   
   TH1D *ZG_optimal_ZA_nominal = new TH1D("ZG_optimal_ZA_nominal"," ",5, xAxis82);
   ZG_optimal_ZA_nominal->SetBinContent(0,0.2648757);
   ZG_optimal_ZA_nominal->SetBinContent(1,28.69619);
   ZG_optimal_ZA_nominal->SetBinContent(2,8.765489);
   ZG_optimal_ZA_nominal->SetBinContent(3,1.567392);
   ZG_optimal_ZA_nominal->SetBinContent(4,1.290171);
   ZG_optimal_ZA_nominal->SetBinContent(5,0.676397);
   ZG_optimal_ZA_nominal->SetBinContent(6,0.1008541);
   ZG_optimal_ZA_nominal->SetBinError(0,0.233453);
   ZG_optimal_ZA_nominal->SetBinError(1,2.069084);
   ZG_optimal_ZA_nominal->SetBinError(2,1.198157);
   ZG_optimal_ZA_nominal->SetBinError(3,0.6336955);
   ZG_optimal_ZA_nominal->SetBinError(4,0.4008868);
   ZG_optimal_ZA_nominal->SetBinError(5,0.402119);
   ZG_optimal_ZA_nominal->SetBinError(6,0.1471924);
   ZG_optimal_ZA_nominal->SetEntries(866);
   ZG_optimal_ZA_nominal->SetFillColor(6);
   ZG_optimal_ZA_nominal->SetLineColor(6);
   ZG_optimal_ZA_nominal->SetMarkerColor(6);
   ZG_optimal_ZA_nominal->GetXaxis()->SetLabelFont(42);
   ZG_optimal_ZA_nominal->GetXaxis()->SetLabelSize(0.035);
   ZG_optimal_ZA_nominal->GetXaxis()->SetTitleSize(0.035);
   ZG_optimal_ZA_nominal->GetXaxis()->SetTitleFont(42);
   ZG_optimal_ZA_nominal->GetYaxis()->SetLabelFont(42);
   ZG_optimal_ZA_nominal->GetYaxis()->SetLabelSize(0.035);
   ZG_optimal_ZA_nominal->GetYaxis()->SetTitleSize(0.035);
   ZG_optimal_ZA_nominal->GetYaxis()->SetTitleFont(42);
   ZG_optimal_ZA_nominal->GetZaxis()->SetLabelFont(42);
   ZG_optimal_ZA_nominal->GetZaxis()->SetLabelSize(0.035);
   ZG_optimal_ZA_nominal->GetZaxis()->SetTitleSize(0.035);
   ZG_optimal_ZA_nominal->GetZaxis()->SetTitleFont(42);
   Mstack->Add(ZG_optimal_ZA_nominal,"");
   Double_t xAxis83[6] = {150, 400, 600, 800, 1000, 1500}; 
   
   TH1D *ZG_optimal_outZA_EWK_nominal = new TH1D("ZG_optimal_outZA_EWK_nominal"," ",5, xAxis83);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(0,0.1003931);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(1,12.64489);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(2,4.735635);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(3,1.736903);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(4,0.6815468);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(5,0.5600731);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(6,0.09536687);
   ZG_optimal_outZA_EWK_nominal->SetBinError(0,0.03556691);
   ZG_optimal_outZA_EWK_nominal->SetBinError(1,0.4040548);
   ZG_optimal_outZA_EWK_nominal->SetBinError(2,0.2490042);
   ZG_optimal_outZA_EWK_nominal->SetBinError(3,0.1508903);
   ZG_optimal_outZA_EWK_nominal->SetBinError(4,0.09470946);
   ZG_optimal_outZA_EWK_nominal->SetBinError(5,0.08554704);
   ZG_optimal_outZA_EWK_nominal->SetBinError(6,0.03611679);
   ZG_optimal_outZA_EWK_nominal->SetEntries(1706);

   ci = TColor::GetColor("#ffff00");
   ZG_optimal_outZA_EWK_nominal->SetFillColor(ci);

   ci = TColor::GetColor("#ffff00");
   ZG_optimal_outZA_EWK_nominal->SetLineColor(ci);

   ci = TColor::GetColor("#ffff00");
   ZG_optimal_outZA_EWK_nominal->SetMarkerColor(ci);
   ZG_optimal_outZA_EWK_nominal->SetMarkerStyle(21);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetLabelFont(42);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetLabelSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetTitleSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetTitleFont(42);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetLabelFont(42);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetLabelSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetTitleSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetTitleFont(42);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetLabelFont(42);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetLabelSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetTitleSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetTitleFont(42);
   Mstack->Add(ZG_optimal_outZA_EWK_nominal,"");
   Mstack->Draw("bar hist");
   Double_t xAxis84[6] = {150, 400, 600, 800, 1000, 1500}; 
   
   TH1D *ZG_optimal_outZA_EWK_nominal = new TH1D("ZG_optimal_outZA_EWK_nominal"," ",5, xAxis84);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(0,0.3651259);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(1,46.41075);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(2,14.80124);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(3,3.759372);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(4,1.922161);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(5,4.531436);
   ZG_optimal_outZA_EWK_nominal->SetBinContent(6,0.1962209);
   ZG_optimal_outZA_EWK_nominal->SetBinError(0,0.2463346);
   ZG_optimal_outZA_EWK_nominal->SetBinError(1,2.444801);
   ZG_optimal_outZA_EWK_nominal->SetBinError(2,1.345874);
   ZG_optimal_outZA_EWK_nominal->SetBinError(3,0.8385044);
   ZG_optimal_outZA_EWK_nominal->SetBinError(4,0.4150341);
   ZG_optimal_outZA_EWK_nominal->SetBinError(5,0.411118);
   ZG_optimal_outZA_EWK_nominal->SetBinError(6,0.1515586);
   ZG_optimal_outZA_EWK_nominal->SetEntries(2867);

   ci = TColor::GetColor("#ff0000");
   ZG_optimal_outZA_EWK_nominal->SetLineColor(ci);
   ZG_optimal_outZA_EWK_nominal->SetLineWidth(2);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetLabelFont(42);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetLabelSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetTitleSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetXaxis()->SetTitleFont(42);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetLabelFont(42);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetLabelSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetTitleSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetYaxis()->SetTitleFont(42);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetLabelFont(42);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetLabelSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetTitleSize(0.035);
   ZG_optimal_outZA_EWK_nominal->GetZaxis()->SetTitleFont(42);
   ZG_optimal_outZA_EWK_nominal->Draw("hist same");
   
   TLegend *leg = new TLegend(0.5,0.78,0.65,0.91,NULL,"brNDC");
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(10);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("ZG_optimal_outZA_EWK_nominal","VBS ZA","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ZG_optimal_ZA_nominal","QCD ZA","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ZG_optimal_outphotonlikejet_mu_mediumlikephoton_nominal","non-prompt","f");
   entry->SetFillColor(7);
   entry->SetFillStyle(1001);
   entry->SetLineColor(7);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ZG_optimal_bkg_nominal","Other Bkg","f");

   ci = TColor::GetColor("#00cc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00cc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ZG_optimal_outZA_EWK_nominal","fT7=-2.00e-12","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.21,0.84,"Preliminary");
tex->SetNDC();
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.21,0.88,"CMS");
tex->SetNDC();
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.76,0.96,"35.862 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   c01->Modified();
   c01->cd();
   c01->SetSelected(c01);
}
