#!/bin/bash
crab submit -c Zcrab/crab3_analysisele_H3.py
crab submit -c Zcrab/crab3_analysisele_H2.py
crab submit -c Zcrab/crab3_analysisele_G.py
crab submit -c Zcrab/crab3_analysisele_F.py
crab submit -c Zcrab/crab3_analysisele_E.py
crab submit -c Zcrab/crab3_analysisele_D.py
crab submit -c Zcrab/crab3_analysisele_C.py
crab submit -c Zcrab/crab3_analysisele_B.py
crab submit -c Zcrab/crab3_analysisDY.py
crab submit -c Zcrab/crab3_analysisSTbart.py
crab submit -c Zcrab/crab3_analysisSTs.py
crab submit -c Zcrab/crab3_analysisST-tbarw.py
crab submit -c Zcrab/crab3_analysisSTt.py
crab submit -c Zcrab/crab3_analysisST-tw.py
crab submit -c Zcrab/crab3_analysisTTA1.py
crab submit -c Zcrab/crab3_analysisTTA2.py
crab submit -c Zcrab/crab3_analysisTTJets.py
crab submit -c Zcrab/crab3_analysisWA1.py
crab submit -c Zcrab/crab3_analysisWA2.py
crab submit -c Zcrab/crab3_analysisWJets1.py
crab submit -c Zcrab/crab3_analysisWJets2.py
crab submit -c Zcrab/crab3_analysisWW1.py
crab submit -c Zcrab/crab3_analysisWW2.py
crab submit -c Zcrab/crab3_analysisWZ1.py
crab submit -c Zcrab/crab3_analysisWZ2.py
crab submit -c Zcrab/crab3_analysisZZ1.py
crab submit -c Zcrab/crab3_analysisZZ2.py
crab submit -c Zcrab/crab3_analysisZA.py
crab submit -c Zcrab/crab3_analysisZA_private.py
crab submit -c Zcrab/crab3_analysisZA_sig.py
